"""Refresh Token

Revision ID: c1bec932b606
Revises: 4a7cf6841c41
Create Date: 2025-02-09 18:26:58.851538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1bec932b606'
down_revision: Union[str, None] = '4a7cf6841c41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('refresh_toke', sa.String(), nullable=True))
    op.add_column('user', sa.Column('date_bird_token', sa.DATETIME(), nullable=True))
    op.add_column('user', sa.Column('data_end_token', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'data_end_token')
    op.drop_column('user', 'date_bird_token')
    op.drop_column('user', 'refresh_toke')
    # ### end Alembic commands ###
